### ISSUE TITLE
 It seems that the "test" folder of the JdbcPostgres project is missing.

### ISSUE THREAD

**Issue by ldev27** [sfa-siard/JdbcPostgres#1]
![JdbcPostgres_test_folder_not_exist](https://user-images.githubusercontent.com/56239351/67615068-6afb7c00-f802-11e9-9a45-771b2b8d44e6.png)

**Comment by HartwigThomas** [comment]
True. The Postgres project is currently being developed and not yet integrated into the main stream of SIARD. But that will change very soon. Until then it is advisable not to work on it.
